'use client'
import { useEffect, useMemo, useState } from 'react'
import { steps, reflectionQuestions } from '@/config/steps'
import { supabase, isSupabaseConfigured } from '@/lib/supabase'
import { clearSession, getLanguage, getSession, saveLanguage, saveSession } from '@/lib/session'
import { translations } from '@/translations'
import type { Employee, Language } from '@/types'
import { Button, ExternalLink, LanguageToggle, ProgressBar, VideoEmbed } from './ui'

const TEAM_URL = 'https://script.google.com/a/macros/99.co/s/AKfycbz_Jc4g49bqxmcxW_6TtCIgv2NFthp6lNEj_Yrk9IE5jd_rxO1taTEKRR3g5B99UtVc/exec?pli=1'
const friendlyTitles: Record<number, string> = { 3: 'Get to know our story, mission and leaders.', 4: 'Get to know our Flywheel, Operations and Systems.', 5: 'Get to know our Values, Culture and Environment.', 6: 'Get to know our Resources, Support and Community.' }

export default function Onboarding() {
  const [language, setLanguage] = useState<Language>('en'); const [employee, setEmployee] = useState<Employee | null>(null)
  const [current, setCurrent] = useState(1); const [completed, setCompleted] = useState<number[]>([]); const [ready, setReady] = useState(false)
  const [email, setEmail] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const t = translations[language]; const step = steps[current - 1]
  useEffect(() => { setLanguage(getLanguage()); const found = getSession(); if (found) { setEmployee(found); hydrate(found) } else setReady(true) }, [])
  const changeLanguage = (l: Language) => { setLanguage(l); saveLanguage(l) }
  async function hydrate(person: Employee) { if (!supabase) { setReady(true); return } const [progress, stepProgress] = await Promise.all([supabase.from('onboarding_progress').select('current_step, completed_at').eq('employee_id', person.id).maybeSingle(), supabase.from('onboarding_step_progress').select('step_number').eq('employee_id', person.id).eq('completed', true)]); if (progress.data) setCurrent(Math.min(progress.data.current_step || 1, 16)); if (stepProgress.data) setCompleted(stepProgress.data.map(x => x.step_number)); setReady(true) }
  async function lookup(e: React.FormEvent) { e.preventDefault(); const normalised = email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(normalised)) { setError(t.emailError); return } if (!supabase || !isSupabaseConfigured) { setError('This site is not configured yet. Please contact the People Team.'); return } setBusy(true); setError(''); const { data } = await supabase.from('employees').select('id,email,name,alias,department,employee_status').eq('email', normalised).maybeSingle(); const status = String(data?.employee_status || '').toLowerCase(); if (!data || status !== 'active') { setError(t.notFound); setBusy(false); return } const person: Employee = { id: data.id, email: data.email, name: data.name, alias: data.alias, department: data.department }; saveSession(person); setEmployee(person); const { data: existing } = await supabase.from('onboarding_progress').select('current_step').eq('employee_id', person.id).maybeSingle(); if (!existing) await supabase.from('onboarding_progress').insert({ employee_id: person.id, current_step: 1, started_at: new Date().toISOString() }); await hydrate(person); setBusy(false) }
  async function persistStep(stepNumber: number, final = false) { if (!employee || !supabase) return true; setBusy(true); const now = new Date().toISOString(); const one = await supabase.from('onboarding_step_progress').upsert({ employee_id: employee.id, step_number: stepNumber, completed: true, completed_at: now }, { onConflict: 'employee_id,step_number' }); const two = await supabase.from('onboarding_progress').upsert({ employee_id: employee.id, current_step: Math.min(stepNumber + 1, 16), ...(final ? { completed_at: now } : {}) }, { onConflict: 'employee_id' }); setBusy(false); if (one.error || two.error) { setError(t.saveError); return false } setCompleted(prev => prev.includes(stepNumber) ? prev : [...prev, stepNumber]); return true }
  async function advance() { setError(''); const final = current === 15; if (await persistStep(current, final)) setCurrent(Math.min(16, current + 1)) }
  function back() { setError(''); setCurrent(Math.max(1, current - 1)) }
  const name = employee?.alias || employee?.name || '99er'
  if (!ready) return <main className="grid min-h-screen place-items-center p-6 text-ink"><p className="animate-pulse">{t.loading}</p></main>
  if (!employee) return <main className="mx-auto grid min-h-screen max-w-xl place-items-center p-6"><section className="w-full rounded-[2rem] bg-white p-7 shadow-soft sm:p-10"><header className="mb-14 flex items-center justify-between"><p className="text-xl font-black tracking-tight">AllAboard!<span className="text-coral">@99</span></p><LanguageToggle language={language} onChange={changeLanguage} /></header><p className="mb-3 text-sm font-bold uppercase tracking-[.16em] text-leaf">99 Group</p><h1 className="text-4xl font-bold tracking-tight sm:text-5xl">{t.emailTitle}</h1><p className="mt-4 max-w-md text-lg leading-relaxed text-ink/70">One person. One journey. One step at a time.</p><form className="mt-10" onSubmit={lookup}><label className="mb-2 block font-semibold" htmlFor="email">{t.emailQuestion}</label><input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder={t.emailPlaceholder} autoComplete="email" className="w-full rounded-2xl border border-ink/20 px-4 py-3.5 transition focus:border-leaf" /><p className="mt-2 min-h-5 text-sm text-red-700" role="alert">{error}</p><Button type="submit" disabled={busy} className="mt-5 w-full">{busy ? t.loading : t.continue}</Button></form></section></main>
  return <main className="mx-auto min-h-screen max-w-6xl p-4 sm:p-8"><header className="mb-6 flex items-center justify-between"><p className="text-xl font-black tracking-tight">AllAboard!<span className="text-coral">@99</span></p><LanguageToggle language={language} onChange={changeLanguage} /></header><div className="grid gap-6 lg:grid-cols-[230px_1fr]"><aside className="order-2 rounded-3xl bg-white/70 p-4 lg:order-1"><p className="font-semibold">{t.journey}</p><p className="mt-1 text-sm text-ink/60">{t.step} {current} {t.of} 16</p><div className="my-4"><ProgressBar current={current} /></div><ol className="grid grid-cols-4 gap-2 lg:grid-cols-1">{steps.map(s => <li key={s.number}><button onClick={() => setCurrent(s.number)} aria-current={current === s.number ? 'step' : undefined} className={`flex w-full items-center gap-2 rounded-xl p-2 text-left text-xs transition ${current === s.number ? 'bg-ink text-white' : completed.includes(s.number) ? 'text-leaf' : 'text-ink/55 hover:bg-ink/5'}`}><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-full border text-[10px] ${completed.includes(s.number) ? 'border-leaf bg-leaf text-white' : ''}`}>{completed.includes(s.number) ? '✓' : s.number}</span><span className="hidden lg:inline">{s.title}</span></button></li>)}</ol><button onClick={() => { clearSession(); setEmployee(null); setCurrent(1); setCompleted([]) }} className="mt-5 text-xs font-semibold text-ink/60 underline">{t.signOut}</button></aside><section className="order-1 min-h-[580px] rounded-[2rem] bg-white p-6 shadow-soft sm:p-10 lg:order-2"><div key={`${current}-${language}`} className="step-enter"><StepContent step={step} employee={employee} t={t} language={language} onAdvance={advance} busy={busy} error={error} setError={setError} /><nav className="mt-10 flex flex-wrap justify-between gap-3 border-t border-ink/10 pt-6">{current > 1 ? <Button variant="secondary" onClick={back}>{t.previous}</Button> : <span />}{current !== 16 && <Button onClick={advance} disabled={busy}>{current === 15 ? t.done : step.optional ? t.skip : t.next}</Button>}</nav></div></section></div></main>
}

function StepContent({ step, employee, t, language, onAdvance, busy, error, setError }: { step: typeof steps[number]; employee: Employee; t: typeof translations.en; language: Language; onAdvance: () => Promise<void>; busy: boolean; error: string; setError: (s: string) => void }) {
  const [question, setQuestion] = useState(''); const [saved, setSaved] = useState(false); const [answers, setAnswers] = useState<Record<string,string>>({}); const [questions, setQuestions] = useState<{step_number:number;question:string}[]>([]); const [copied, setCopied] = useState(false)
  useEffect(() => { if (step.kind === 'manager' && supabase) supabase.from('onboarding_questions').select('step_number,question').eq('employee_id', employee.id).in('step_number', [3,4,5,6]).then(({data}) => setQuestions(data || [])) }, [step.kind, employee.id])
  async function saveQuestion() { if (!question.trim() || !supabase) return; setError(''); const { error } = await supabase.from('onboarding_questions').insert({ employee_id: employee.id, step_number: step.number, question: question.trim() }); if (error) { setError(t.saveError); return } setQuestion(''); setSaved(true) }
  async function saveReflections() { if (!supabase) return; const records = Object.entries(answers).filter(([, answer]) => answer.trim()).map(([question, answer]) => ({ employee_id: employee.id, question, answer })); if (!records.length) return; const { error } = await supabase.from('onboarding_reflections').insert(records); if (error) setError(t.saveError) }
  const managerMessage = `Hi,\n\nI have a few questions from my AllAboard!@99 onboarding:\n\n${questions.map(q => `• ${q.question}`).join('\n') || 'No questions this time.'}\n\nThanks!`
  if (step.number === 2) return <><p className="text-sm font-bold uppercase tracking-[.16em] text-leaf">99 Group</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Welcome, {employee.alias || employee.name || '99er'}.</h1><p className="mt-5 max-w-xl text-lg leading-relaxed text-ink/70">Welcome to 99 Group. You’re joining the {employee.department || '99 Group'} team, and we’re very glad you’re here.</p><ExternalLink href={TEAM_URL} className="mt-8">{t.team}</ExternalLink></>
  if (step.kind === 'video') return <><p className="text-sm font-bold uppercase tracking-[.16em] text-leaf">{t.step} {step.number}</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{friendlyTitles[step.number]}</h1><div className="mt-8">{step.videoId && <VideoEmbed id={step.videoId} title={step.title} />}</div><label className="mt-7 block font-semibold">{t.question}<textarea value={question} onChange={e => { setQuestion(e.target.value); setSaved(false) }} placeholder={t.questionPlaceholder} className="mt-2 min-h-28 w-full rounded-2xl border border-ink/20 p-4" /></label><Button variant="secondary" onClick={saveQuestion} disabled={!question.trim()} className="mt-3">{saved ? t.saved : t.saveQuestion}</Button></>
  if (step.kind === 'reflection') return <><h1 className="text-4xl font-bold tracking-tight">A note to your future self.</h1><p className="mt-4 max-w-2xl leading-relaxed text-ink/70">{t.reflection}</p><div className="mt-7 space-y-5">{reflectionQuestions.map(q => <label key={q} className="block font-semibold">{q}<textarea value={answers[q] || ''} onChange={e => setAnswers({...answers,[q]:e.target.value})} className="mt-2 min-h-24 w-full rounded-2xl border border-ink/20 p-4 font-normal" /></label>)}</div><Button variant="secondary" onClick={saveReflections} className="mt-4">{t.done}</Button></>
  if (step.kind === 'manager') return <><h1 className="text-4xl font-bold tracking-tight">Questions for your manager.</h1><p className="mt-4 leading-relaxed text-ink/70">{t.manager}</p><div className="mt-7 rounded-2xl bg-ink/5 p-5 whitespace-pre-wrap">{questions.length ? managerMessage : t.noQuestions}</div><div className="mt-4 flex gap-3"><Button variant="secondary" onClick={() => { navigator.clipboard.writeText(managerMessage); setCopied(true) }}>{copied ? t.copied : t.copyQuestions}</Button><ExternalLink href="https://app.slack.com/client">{t.openSlack}</ExternalLink></div></>
  if (step.kind === 'complete') return <><div className="grid h-16 w-16 place-items-center rounded-full bg-leaf text-3xl text-white">✓</div><h1 className="mt-6 text-5xl font-bold tracking-tight">You’re all set.</h1><p className="mt-4 max-w-xl text-lg leading-relaxed text-ink/70">Now you are ready for your #YourWayHome journey.</p><p className="mt-8 rounded-2xl bg-leaf/10 p-4 font-semibold text-leaf">{t.allDone}</p></>
  if (step.kind === 'thanks') return <><div className="text-6xl">✦</div><h1 className="mt-5 text-5xl font-bold tracking-tight">Thank you.</h1><p className="mt-4 max-w-xl text-lg leading-relaxed text-ink/70">Your AllAboard!@99 journey is complete. We’re excited to have you with us.</p>{step.externalUrl && <ExternalLink href={step.externalUrl} className="mt-8">{t.checkPlatforms}</ExternalLink>}</>
  if (step.kind === 'form') return <><h1 className="text-4xl font-bold tracking-tight">Fill out your Declaration Form.</h1><p className="mt-4 text-ink/70">{t.formFallback}</p><div className="mt-7 overflow-hidden rounded-3xl border border-ink/10"><iframe title="Declaration Form" className="h-[390px] w-full" src={step.externalUrl} loading="lazy" /></div>{step.externalUrl && <ExternalLink href={step.externalUrl} className="mt-5">Open Declaration Form</ExternalLink>}</>
  if (step.kind === 'linkedin') return <><h1 className="text-4xl font-bold tracking-tight">Update your LinkedIn profile.</h1><p className="mt-4 max-w-2xl text-lg leading-relaxed text-ink/70">Share your 99er journey with a fresh profile banner or a SuperTwibbon. Your People Team badge can live here when it’s ready.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><ExternalLink href="https://sites.google.com/99.co/99ers-home/brand-assets-templates">Open banner resources</ExternalLink><ExternalLink href="https://www.supertwibbon.com/99ersLinkedInProfile">Open SuperTwibbon</ExternalLink></div><div className="mt-7 grid aspect-[3/1] place-items-center rounded-3xl border-2 border-dashed border-ink/20 bg-ink/[.02] text-sm text-ink/55">People Team badge preview</div>{step.externalUrl && <ExternalLink href={step.externalUrl} className="mt-6">Edit your LinkedIn profile</ExternalLink>}</>
  const details: Record<number, { title: string; copy: string; action: string }> = { 1: { title: 'Welcome aboard.', copy: 'One person. One journey. One step at a time.', action: '' }, 7: { title: 'Update your Slack profile.', copy: 'To help everyone recognise and connect with you easily, please update your profile photo, add your manager, and include your role and department.', action: t.openSlack }, 10: { title: 'Set up your email signature.', copy: 'Use the shared template to make your email recognisably 99.', action: 'Open email signature template' }, 11: { title: 'Add your onboarding meetings to Google Calendar.', copy: 'Keep the important moments in your first few weeks close at hand.', action: 'Open Google Calendar' }, 12: { title: 'You’re almost all set.', copy: 'From here, 99ers Home has everything else — benefits, forms, and the processes you may use along the way.', action: 'Explore 99ers Home' } }
  const detail = details[step.number] || { title: step.title, copy: '', action: t.resource }; return <><p className="text-sm font-bold uppercase tracking-[.16em] text-leaf">{t.step} {step.number}</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{detail.title}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-ink/70">{detail.copy}</p>{step.externalUrl && <ExternalLink href={step.externalUrl} className="mt-8">{detail.action}</ExternalLink>}{error && <p className="mt-4 text-sm text-red-700" role="alert">{error}</p>}</>
}
