import type { Language } from '@/types'
const en = {
  emailTitle: 'Welcome aboard.', emailQuestion: "What's your work email?", emailPlaceholder: 'your.name@99.co', continue: 'Continue', previous: 'Previous', next: 'Next', done: 'Done', skip: 'Skip', open: 'Open', step: 'Step', of: 'of', journey: 'Your onboarding journey', loading: 'Getting your journey ready…', emailError: 'Please enter a valid work email.', notFound: "We couldn't find an active onboarding record for this email. Please check your work email or contact the People Team.", saveError: 'We could not save that just now. Please try again.', question: "Have a question? Note it down here and we'll save it for you to ask your manager later.", questionPlaceholder: 'Write your question here…', saveQuestion: 'Save question', saved: 'Saved', openSlack: 'Open Slack', copyQuestions: 'Copy questions', copied: 'Copied!', team: "See who's in your team", allDone: 'Your onboarding is complete. The People Team has been notified.', noQuestions: "You didn't leave any questions — that's perfectly fine.", checkPlatforms: 'Check out our platforms', resource: 'Open resource', signOut: 'Use another email', progress: 'Progress', formFallback: 'If the form does not load here, you can complete it in a new tab.', reflection: 'Take a quiet moment to answer any of these prompts. Your answers are for a future 30-day check-in.', manager: 'Here are the questions you collected along the way. Copy this note, then send it to your manager in Slack.', language: 'Language'
}
const id: typeof en = {
  emailTitle: 'Selamat bergabung.', emailQuestion: 'Apa email kerja Anda?', emailPlaceholder: 'nama.anda@99.co', continue: 'Lanjutkan', previous: 'Sebelumnya', next: 'Berikutnya', done: 'Selesai', skip: 'Lewati', open: 'Buka', step: 'Langkah', of: 'dari', journey: 'Perjalanan onboarding Anda', loading: 'Menyiapkan perjalanan Anda…', emailError: 'Masukkan email kerja yang valid.', notFound: 'Kami tidak dapat menemukan data onboarding aktif untuk email ini. Periksa kembali email kerja Anda atau hubungi tim People.', saveError: 'Kami belum dapat menyimpan ini. Silakan coba lagi.', question: 'Ada pertanyaan? Tulis di sini dan kami akan menyimpannya untuk Anda tanyakan kepada manajer nanti.', questionPlaceholder: 'Tulis pertanyaan Anda di sini…', saveQuestion: 'Simpan pertanyaan', saved: 'Tersimpan', openSlack: 'Buka Slack', copyQuestions: 'Salin pertanyaan', copied: 'Tersalin!', team: 'Lihat siapa saja di tim Anda', allDone: 'Onboarding Anda selesai. Tim People telah diberi tahu.', noQuestions: 'Anda tidak meninggalkan pertanyaan — tidak apa-apa.', checkPlatforms: 'Lihat platform kami', resource: 'Buka sumber', signOut: 'Gunakan email lain', progress: 'Progres', formFallback: 'Jika formulir tidak muncul di sini, Anda dapat mengisinya di tab baru.', reflection: 'Luangkan waktu sejenak untuk menjawab pertanyaan ini. Jawaban Anda akan digunakan untuk check-in 30 hari.', manager: 'Berikut pertanyaan yang Anda kumpulkan. Salin pesan ini, lalu kirimkan kepada manajer Anda di Slack.', language: 'Bahasa'
}
export const translations = { en, id }
export type Translation = typeof en
